### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ilarijn** [hannuorn/Huutokauppa#1]
**Koodikatselmointi tehty 26.11.2019 klo 16 olemassaolleiden GitHub-materiaalien ja Heroku-sovelluksen perusteella.**

Itse koodi oli siistiä ja helppolukuista. Sen seuraamisessa muuttujanimien tai jäsentelyn osalta ei ollut ongelmia.

Sovellus toimi tähän mennessä toteutettujen toimintojen osalta enimmäkseen odotetusti, ja sen käyttäminen oli helppoa. Kävin toiminnot läpi luoden uuden käyttäjän, jolla loin kaksi huutokauppaa ja tein huutoja. 

Autentikointi toimi eikä huutokauppoja päässyt lisäämään kirjautumattomana. Toisaalta ilman kirjautumista ei myöskään päässyt tarkastelemaan yksittäisen huutokaupan sisältöä. Käyttäjän luontiin ei liittynyt muita validointeja kuin olemassaoleva käyttäjänimi. Tietokannan puolella voisi ehkä olla hyvä asettaa käyttäjänimelle UNIQUE-rajoite.

Hiukan odotustenvastaisesti löytyi mahdollisuus tehdä huuto omaan huutokauppaan. My Account -valinta käyttäjävalikossa myös kirjasi ulos.

Kokeilun aikana ilmenivät seuraavat bugit:

- Sovellukseen pystyi kirjautumaan tyhjillä kirjautumislomakkeen kentillä päästen autentikoidun käyttäjän toimintoihin.

- Liian suuri luku huutokentässä uutta huutoa luodessa antoi Internal Server Error -sivun.

- Huutokaupan pystyi luomaan negatiivisella minimihuudolla.

Muuta huomautettavaa en löytänyt. Tsemppiä tuleville viikoille!

**Comment by hannuorn** [comment]
Kiitos mainioista löydöistä ja palautteesta!
